In [88]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [89]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-dat

True

In [90]:
import numpy  as np
import pandas as pd
import math
import scipy
import os
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag
import  pickle as pickle
import tqdm as tqdm
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
from collections import Counter
import numpy as np
from scipy.stats import bernoulli, binom

In [91]:


#


file_path = os.path.join("C:\\Users\\User\\Desktop\\SPRING 2023\\EEE 486\\Assignment3")
dost_file = os.path.join(file_path, "Fyodor_Dostoyevski_Processed.txt")
# with open("Fyodor_Dostoyevski_Processed.txt", encoding="utf8", mode="r") as f:
#     lines = f.read()
# pos_tagged = pos_tag(word_tokenize(lines), tagset='universal')
# print(pos_tagged)
#
# with open("pos_tagged_txt.pkl", "wb") as f:
#     pickle.dump(pos_tagged, f)

with open("/content/drive/MyDrive/NLP Ödev 3/pos_tagged_txt.pkl", "rb") as f:
    pos_tagged = pickle.load(f)
class custom_lemmatizer:

    tag_dict = {"ADJ": wordnet.ADJ,
                "NOUN": wordnet.NOUN}

    lemmatizer = WordNetLemmatizer()

    def lemmatize(self, word_pos_tuple):
        word = word_pos_tuple[0]
        pos_tag = word_pos_tuple[1]
        if pos_tag in self.tag_dict:
            return self.lemmatizer.lemmatize(word, self.tag_dict[pos_tag]).lower()
        else:
            return word.lower()


cm = custom_lemmatizer()


lemmatized = [[cm.lemmatize(t),t[1]] for t in pos_tagged]
print()

In [92]:
with open("/content/drive/MyDrive/NLP Ödev 3/Fyodor_Dostoyevski_Processed.txt", encoding="utf8", mode="r") as f:
    lines = f.read()
len(lines.split())

1152279

In [ ]:
lines.split()

['part',
 'i',
 'chapter',
 'i',
 'on',
 'an',
 'exceptionally',
 'hot',
 'evening',
 'early',
 'in',
 'july',
 'a',
 'young',
 'man',
 'came',
 'out',
 'of',
 'the',
 'garret',
 'in',
 'which',
 'he',
 'lodged',
 'in',
 's.',
 'place',
 'and',
 'walked',
 'slowly,',
 'as',
 'though',
 'in',
 'hesitation,',
 'towards',
 'k.',
 'bridge.',
 'he',
 'had',
 'successfully',
 'avoided',
 'meeting',
 'his',
 'landlady',
 'on',
 'the',
 'staircase.',
 'his',
 'garret',
 'was',
 'under',
 'the',
 'roof',
 'of',
 'a',
 'high,',
 'five-storied',
 'house',
 'and',
 'was',
 'more',
 'like',
 'a',
 'cupboard',
 'than',
 'a',
 'room.',
 'the',
 'landlady',
 'who',
 'provided',
 'him',
 'with',
 'garret,',
 'dinners,',
 'and',
 'attendance,',
 'lived',
 'on',
 'the',
 'floor',
 'below,',
 'and',
 'every',
 'time',
 'he',
 'went',
 'out',
 'he',
 'was',
 'obliged',
 'to',
 'pass',
 'her',
 'kitchen,',
 'the',
 'door',
 'of',
 'which',
 'invariably',
 'stood',
 'open.',
 'and',
 'each',
 'time',
 'he',


In [93]:
df_lemm = pd.DataFrame(lemmatized)

In [94]:
len(df_lemm)

1425758

In [100]:
len(df_lemm[df_lemm[0]=="that"])


19429

In [101]:
def bigram_by_step(lst, step= 1):
  """
  fow window size of 1, give step = 2
  """
  bigram_2 = []
  bigram_2_tags = []
  step_size = []
  for j in np.arange(step)[1:]:
    for i in tqdm.tqdm(range(len(lst)-step)):
        bigram_2.append((lst[i][0], lst[i+step-j][0] ))
        bigram_2_tags.append( [lst[i][1], lst[i+step-j][1]])
        step_size.append(step-j)

  bigram_df = pd.concat([pd.DataFrame(bigram_2, columns = ["w1","w2"]), pd.DataFrame(bigram_2_tags, columns = ["w1_t", "w2_t"]), pd.DataFrame(step_size, columns = ["length"])], axis = 1)
  return bigram_df

In [102]:
single_bigram = bigram_by_step(lemmatized, step = 2)
double_bigram = bigram_by_step(lemmatized, step = 4)

100%|██████████| 1425754/1425754 [00:03<00:00, 442098.13it/s]


In [104]:
single_bigram[(single_bigram["w1"]=="magnificent") & (single_bigram["w2"]=="capital")]

double_bigram[(double_bigram["w1"]=="bright") & (double_bigram["w2"]=="fire")]


w1    w2 w1_t  w2_t  length
1400234  bright  fire  ADJ  NOUN       3

In [105]:
single_bigram[(single_bigram["w1"]=="mr.")& (single_bigram["w2"]=="skimpole") ]


Empty DataFrame
Columns: [w1, w2, w1_t, w2_t, length]
Index: []

In [106]:
double_bigram[(double_bigram["w1"]=="spontaneous")& (double_bigram["w2"]=="combustion") ]


w1          w2 w1_t  w2_t  length
2926706  spontaneous  combustion  ADJ  NOUN       1

In [ ]:
with open("/content/drive/MyDrive/NLP Ödev 3/stop_words.txt", "r") as f:
  stop_wrds = f.read()
stop_wrds  = stop_wrds.split("\n")

In [ ]:
def preprocess_bigrams(df,stop_words, df_lemm):
  freq_dict = (df_lemm[0].value_counts()).to_dict()
  bigram_freq = []
  df_new = df[((df["w1_t"] == "NOUN") & (df["w2_t"]== "NOUN")) | ( (df["w1_t"] == "ADJ") & (df["w2_t"]== "NOUN"))]
  for word in stop_words:
    df_new = df_new[(df_new["w1"] != word) & (df_new["w2"] != word) ]
  df_new_new = df_new.reset_index()
  df_new_new = df_new_new.drop(columns = ["index"])
  for i in tqdm.tqdm(range(df_new_new.shape[0])):
   

    if ((df_new_new[df_new_new.index == i].iloc[:, 0]).values[0].isalpha() and (df_new_new[df_new_new.index == i].iloc[:, 1]).values[0].isalpha()):
      pass
    else:
      df_new_new = df_new_new.drop(i)

  
  counts = pd.DataFrame(df_new_new.iloc[:,:2].value_counts())
  counts= counts.reset_index()
  counts.columns = ["w1","w2","c(w1w2)"]
  counts_new = counts[counts["c(w1w2)"] >= 10]
  last_colloc = counts_new.iloc[:,:3]

  for i in tqdm.tqdm(range(last_colloc.shape[0])):
    bigram_freq.append((freq_dict[last_colloc[last_colloc.index == i].iloc[:, 0].values[0]],freq_dict[last_colloc[last_colloc.index == i].iloc[:, 1].values[0]]))

  last_colloc = pd.concat([last_colloc, pd.DataFrame(bigram_freq, columns = ["c(w1)", "c(w2)"])], axis=1)

  return last_colloc

In [ ]:
single_counts = preprocess_bigrams(single_bigram,stop_wrds, df_lemm)

  3%|▎         | 1959/66307 [00:09<04:59, 215.09it/s]


KeyboardInterrupt: ignored

In [ ]:
triple_counts = preprocess_bigrams(double_bigram,stop_wrds, df_lemm)

100%|██████████| 527/527 [00:00<00:00, 1448.89it/s]


In [ ]:
#  with open("/content/drive/MyDrive/NLP Ödev 3/triple_counts.pkl", "wb") as f:
#      pickle.dump(triple_counts, f)
#

In [ ]:
# with open("/content/drive/MyDrive/NLP Ödev 3/single_counts.pkl", "wb") as f:
#    pickle.dump(single_counts, f)

In [ ]:
triple_counts = pd.read_pickle("/content/drive/MyDrive/NLP Ödev 3/triple_counts.pkl")
single_counts = pd.read_pickle("/content/drive/MyDrive/NLP Ödev 3/single_counts.pkl")


In [ ]:
triple_counts

w1            w2  c(w1w2)  c(w1)  c(w2)
0      pyotr  stepanovitch      427    834    509
1     stepan  trofimovitch      412    525    513
2    varvara      petrovna      331    474    507
3        old           man      290   1356   2546
4     fyodor    pavlovitch      246    306    461
..       ...           ...      ...    ...    ...
522       ll    understand       10   1159    909
523    equal       footing       10     64     32
524   rouble        copeck       10    543     56
525     high       society       10    285    245
526    young        friend       10    776    606

[527 rows x 5 columns]

In [107]:
def t_test(df, df_all, step = 1):
  if step !=3:
    null_hyp_w1 = df["c(w1)"]/len(df_all)
    null_hyp_w2 = df["c(w2)"]/len(df_all)
    null = null_hyp_w1.mul(null_hyp_w2.values)    

    p = df["c(w1w2)"]/len(df_all)
    mean, var = bernoulli.stats(p)
    t_score = -(null-mean ) / (np.sqrt(var/(len(df_all))))  
  else:
    null_hyp_w1 = df["c(w1)"]/(len(df_all))
    null_hyp_w2 = df["c(w2)"]/(len(df_all))
    null = null_hyp_w1.mul(null_hyp_w2.values)    

    p = df["c(w1w2)"]/(3*len(df_all))
    mean, var = bernoulli.stats(p)
    t_score = -(null-mean ) / (np.sqrt(var/(3*len(df_all))))  
  t_score = pd.DataFrame(t_score)
  t_score.columns = ["t_score"]
  df =pd.concat([df,t_score],axis=1 )

  return df                 


In [116]:
W1W2 =  t_sorted_score_single[ (t_sorted_score_single["w1"] == "great") & (t_sorted_score_single["w2"] == "man")].iloc[:,3]

W1 =   t_sorted_score_single[ (t_sorted_score_single["w1"] == "great") & (t_sorted_score_single["w2"] == "man")].iloc[:,4]
W2 =   t_sorted_score_single[ (t_sorted_score_single["w1"] == "great") & (t_sorted_score_single["w2"] == "man")].iloc[:,5]

null_hyp_w1 = W1/len(df_lemm)
null_hyp_w2 = W2/len(df_lemm)
null = null_hyp_w1.mul(null_hyp_w2.values)    

p = W1W2/len(df_lemm)
mean, var = bernoulli.stats(p)
t_score = (mean-null ) / (np.sqrt(var/(len(df_lemm))))  

In [ ]:
 t_sorted_score_single[ (t_sorted_score_single["w1"] == "stepan") & (t_sorted_score_single["w2"] == "trofimovitch")]

Unnamed: 0      w1            w2  c(w1w2)  c(w1)  c(w2)    t_score
1           1  stepan  trofimovitch      412    525    513  20.291409

In [ ]:
null, p

(217    0.000002
 Name: c(w1), dtype: float64,
 217    0.000013
 Name: c(w1w2), dtype: float64)

In [ ]:
t_score = (p-null) / (np.sqrt(p/(len(df_lemm))))  

In [117]:
t_score

217    34.684303
Name: c(w2), dtype: float64

In [120]:
t_sorted_score_single[ (t_sorted_score_single["w1"] == "head") & (t_sorted_score_single["w2"] == "clerk")]

w1     w2  c(w1w2)  c(w1)  c(w2)   t_score
129  head  clerk       22    801    136  4.674162

In [ ]:
p

129    0.000015
Name: c(w1w2), dtype: float64

In [ ]:
mean

array([1.54303886e-05])

In [108]:
t_score_single = t_test(single_counts, df_lemm)

In [109]:
t_score_single

w1            w2  c(w1w2)  c(w1)  c(w2)    t_score
0       pyotr  stepanovitch      427    834    509  20.652663
1      stepan  trofimovitch      412    525    513  20.291409
2     varvara      petrovna      331    474    507  18.186252
3         old           man      289   1356   2546  16.859272
4      fyodor    pavlovitch      246    306    461  15.679432
..        ...           ...      ...    ...    ...        ...
352     great        writer       10   1202     30   3.154291
353     great        number       10   1202    113   3.132163
354  peculiar           way       10     99   1198   3.135983
355   several        people       10    212   1135   3.108920
356     whole       evening       10    889    466   3.070404

[357 rows x 6 columns]

In [ ]:
 t_sorted_score_single[ (t_sorted_score_single["w1"] == "great") & (t_sorted_score_single["w2"] == "man")]

Unnamed: 0     w1   w2  c(w1w2)  c(w1)  c(w2)   t_score
217         217  great  man       18   1202   2546  3.736745

In [110]:
t_score_triple = t_test(triple_counts, df_lemm,step =3)

In [111]:
t_score_triple

w1            w2  c(w1w2)  c(w1)  c(w2)    t_score
0      pyotr  stepanovitch      427    834    509  20.621782
1     stepan  trofimovitch      412    525    513  20.270840
2    varvara      petrovna      331    474    507  18.166315
3        old           man      290   1356   2546  16.603375
4     fyodor    pavlovitch      246    306    461  15.665913
..       ...           ...      ...    ...    ...        ...
522       ll    understand       10   1159    909   2.461273
523    equal       footing       10     64     32   3.160919
524   rouble        copeck       10    543     56   3.142048
525     high       society       10    285    245   3.115821
526    young        friend       10    776    606   2.849378

[527 rows x 6 columns]

In [112]:
t_sorted_score_triple = t_score_triple.sort_values(by=['t_score'], ascending = False)
t_sorted_score_triple = t_sorted_score_triple.reset_index()
t_sorted_score_triple = t_sorted_score_triple.drop(columns = ["index"])
t_sorted_score_triple.to_csv("/content/drive/MyDrive/NLP Ödev 3/T-score_triple.csv")

In [113]:
t_sorted_score_single = t_score_single.sort_values(by=['t_score'], ascending = False)
t_sorted_score_single = t_sorted_score_single.reset_index()
t_sorted_score_single = t_sorted_score_single.drop(columns = ["index"])
t_sorted_score_single.to_csv("/content/drive/MyDrive/NLP Ödev 3/T-score_single.csv")

In [115]:
t_sorted_score_triple.iloc[:20]

w1               w2  c(w1w2)  c(w1)  c(w2)    t_score
0       pyotr     stepanovitch      427    834    509  20.621782
1      stepan     trofimovitch      412    525    513  20.270840
2     varvara         petrovna      331    474    507  18.166315
3         old              man      290   1356   2546  16.603375
4      fyodor       pavlovitch      246    306    461  15.665913
5    katerina         ivanovna      229    427    635  15.095448
6       young              man      234    776   2546  15.025708
7    nastasia       philipovna      215    417    251  14.648227
8         old            woman      215   1356   1047  14.459508
9     nikolay  vsyevolodovitch      198    518    312  14.047405
10      great             deal      165   1202    237  12.798815
11          o            clock      157    225    193  12.522902
12         ha               ha      144    252    252  11.989067
13      pyotr       petrovitch      143    834    331  11.909886
14  lizabetha      prokofievna      136    185    177  11.656181
15       long             time      147   1074   2623  11.635656
16     dmitri     fyodorovitch      126    427    327  11.198963
17       next              day      119    356   1711  10.791372
18      first             time      130   1297   2623  10.774088
19        old             lady      119   1356    681  10.730743

In [ ]:
t_sorted_score_single = pd.read_csv("/content/drive/MyDrive/NLP Ödev 3/T-score_single.csv")
t_sorted_score_triple = pd.read_csv("/content/drive/MyDrive/NLP Ödev 3/T-score_triple.csv")

In [ ]:
t_sorted_score_single.iloc[:20]

Unnamed: 0         w1               w2  c(w1w2)  c(w1)  c(w2)    t_score
0            0      pyotr     stepanovitch      427    834    509  20.652663
1            1     stepan     trofimovitch      412    525    513  20.291409
2            2    varvara         petrovna      331    474    507  18.186252
3            3        old              man      289   1356   2546  16.859272
4            4     fyodor       pavlovitch      246    306    461  15.679432
5            5      young              man      232    776   2546  15.141801
6            6   katerina         ivanovna      229    427    635  15.121393
7            7   nastasia       philipovna      215    417    251  14.658977
8            8        old            woman      208   1356   1047  14.354208
9            9    nikolay  vsyevolodovitch      198    518    312  14.064168
10          10      great             deal      164   1202    237  12.791382
11          11      pyotr       petrovitch      143    834    331  11.942668
12          12       long             time      143   1074   2623  11.793622
13          13  lizabetha      prokofievna      136    185    177  11.660491
14          14     dmitri     fyodorovitch      126    427    327  11.216743
15          15      first             time      130   1297   2623  11.192988
16          16        old             lady      119   1356    681  10.849792
17          17       next              day      117    356   1711  10.777599
18          18    evgenie       pavlovitch      106    227    461  10.288884
19          19      yulia       mihailovna      105    215    202  10.244355

In [ ]:
t_sorted_score_single[ (t_sorted_score_single["w1"] == "head") & (t_sorted_score_single["w2"] == "clerk")]

Unnamed: 0    w1     w2  c(w1w2)  c(w1)  c(w2)   t_score
121         121  head  clerk       22    801    136  4.687686

In [ ]:
t_sorted_score_single[ (t_sorted_score_single["w1"] == "great") & (t_sorted_score_single["w2"] == "man")]

Unnamed: 0     w1   w2  c(w1w2)  c(w1)  c(w2)   t_score
217         217  great  man       18   1202   2546  3.736745

In [ ]:
t_sorted_score_single[ (t_sorted_score_single["w1"] == "head") & (t_sorted_score_single["w2"] == "clerk")]

Unnamed: 0    w1     w2  c(w1w2)  c(w1)  c(w2)   t_score
129         129  head  clerk       22    801    136  4.674162

In [ ]:
len(df_lemm)

1425758

In [ ]:
def chi_square_test(bigram, bigram_all):

  o11 = bigram["c(w1w2)"] / len(bigram_all)
  o22 = (len(bigram_all) - bigram["c(w1w2)"]) / len(bigram_all)
  o12 = (bigram["c(w2)"] - bigram["c(w1w2)"]) / len(bigram_all)
  o21 = (bigram["c(w1)"] - bigram["c(w1w2)"]) / len(bigram_all)
  X2 = pd.DataFrame((len(bigram_all) * (o11*o22 - o12*o21)**2) / ((o11 + o12) * (o11 + o21) * (o12 + o22) * (o21 + o22)))
  X2.columns = ["chi-square_score"]
  bigram = pd.concat([bigram, X2], axis=1)
  return bigram   

In [ ]:
chi_single = chi_square_test(single_counts, single_bigram)
chi_triple = chi_square_test(triple_counts, double_bigram)

In [ ]:
w1 = chi_single[ (chi_single["w1"] == "head") & (chi_single["w2"] == "clerk")].iloc[:,3]
w2 = chi_single[ (chi_single["w1"] == "head") & (chi_single["w2"] == "clerk")].iloc[:,4]

w1w2 = chi_single[ (chi_single["w1"] == "head") & (chi_single["w2"] == "clerk")].iloc[:,2]

o11=w1w2 / len(single_bigram)
o22 = (len(single_bigram) - w1w2) / len(single_bigram)
o12 = (w2 -w1w2) / len(single_bigram)
o21 = (w1 - w1w2) / len(single_bigram)
X2 = pd.DataFrame((len(single_bigram) * (o11*o22 - o12*o21)**2) / ((o11 + o12) * (o11 + o21) * (o12 + o22) * (o21 + o22)))

In [ ]:
w1 = chi_single[ (chi_single["w1"] == "great") & (chi_single["w2"] == "man")].iloc[:,3]
w2 = chi_single[ (chi_single["w1"] == "great") & (chi_single["w2"] == "man")].iloc[:,4]

w1w2 = chi_single[ (chi_single["w1"] == "great") & (chi_single["w2"] == "man")].iloc[:,2]

o11=w1w2 / len(single_bigram)
o22 = (len(single_bigram) - w1w2) / len(single_bigram)
o12 = (w2 -w1w2) / len(single_bigram)
o21 = (w1 - w1w2) / len(single_bigram)
X2 = pd.DataFrame((len(single_bigram) * (o11*o22 - o12*o21)**2) / ((o11 + o12) * (o11 + o21) * (o12 + o22) * (o21 + o22)))

In [ ]:
chi_single[ (chi_single["w1"] == "great") & (chi_single["w2"] == "man")]


w1   w2  c(w1w2)  c(w1)  c(w2)  chi-square_score
162  great  man       18   1202   2546        117.484644

In [ ]:
len(single_bigram)

1425756

In [ ]:
o11,o22,o12,o21,

(162    0.000013
 Name: c(w1w2), dtype: float64,
 162    0.999987
 Name: c(w1w2), dtype: float64,
 162    0.001773
 dtype: float64,
 162    0.00083
 dtype: float64)

In [ ]:
chi_single[ (chi_single["w1"] == "head") & (chi_single["w2"] == "clerk")]

w1     w2  c(w1w2)  c(w1)  c(w2)  chi-square_score
127  head  clerk       22    801    136       6294.837113

In [ ]:
chi_single[ (chi_single["w1"] == "great") & (chi_single["w2"] == "man")]

w1   w2  c(w1w2)  c(w1)  c(w2)  chi-square_score
162  great  man       18   1202   2546        117.484644

In [ ]:
chi_sorted_triple = chi_triple.sort_values(by=['chi-square_score'], ascending = False)
chi_sorted_triple = chi_sorted_triple.reset_index()
chi_sorted_triple = chi_sorted_triple.drop(columns = ["index"])
chi_sorted_single.to_csv("/content/drive/MyDrive/NLP Ödev 3/chi-score_single.csv")

In [ ]:
chi_sorted_single = chi_single.sort_values(by=['chi-square_score'], ascending = False)
chi_sorted_single = chi_sorted_single.reset_index()
chi_sorted_single = chi_sorted_single.drop(columns = ["index"])
chi_sorted_single.to_csv("/content/drive/MyDrive/NLP Ödev 3/chi-score_triple.csv")

In [ ]:
chi_sorted_single

w1             w2  c(w1w2)  c(w1)  c(w2)  chi-square_score
0    rodion    romanovitch       80     97     82      1.147185e+06
1    mihail    makarovitch       20     25     21      1.086285e+06
2    trifon   borissovitch       35     45     39      9.951744e+05
3    stepan   trofimovitch      412    525    513      8.984231e+05
4       lef  nicolaievitch       33     43     41      8.806712e+05
..      ...            ...      ...    ...    ...               ...
352   whole           time       13    889   2623      7.921682e+01
353  little           hand       11   1465   1578      5.440218e+01
354  little            man       12   1465   2546      3.380743e+01
355  little            one       17   1465   4597      3.214601e+01
356  little           time       11   1465   2623      2.571057e+01

[357 rows x 6 columns]

In [ ]:
def likelihood_test(bigram, bigram_all):
  scores = []
  for i in range(len(bigram)):

    p= bigram["c(w2)"].iloc[i] / len(bigram_all)
    b_1 = binom.pmf(bigram["c(w1w2)"].iloc[i], bigram["c(w1)"].iloc[i], p)
    b_not_1 = binom.pmf((bigram["c(w2)"].iloc[i] - bigram["c(w1w2)"].iloc[i]), (len(bigram_all)- bigram["c(w1)"].iloc[i]), p)
    L_H1 = b_1 * b_not_1
    
    p_1 = bigram["c(w1w2)"].iloc[i] / bigram["c(w1)"].iloc[i]
    P_2 = (bigram["c(w2)"].iloc[i] - bigram["c(w1w2)"].iloc[i]) / (len(bigram_all)- bigram["c(w1)"].iloc[i])
    b_1_dep = binom.pmf(bigram["c(w1w2)"].iloc[i], bigram["c(w1)"].iloc[i], p_1)
    b_not_1_dep = binom.pmf((bigram["c(w2)"].iloc[i] - bigram["c(w1w2)"].iloc[i]), (len(bigram_all)- bigram["c(w1)"].iloc[i]), P_2)
    L_H2 = b_1_dep * b_not_1_dep
    if L_H1 == 0:
      L_H1 = 1e-40
    score = -2* np.log(L_H1/ L_H2)

    scores.append(score)

  scores = pd.DataFrame(scores, columns = [r"-2log(λ)"])
  bigram = pd.concat([bigram, scores], axis = 1)
  return bigram



In [ ]:
W1W2 = L_single[(L_single["w1"] == "head") & (L_single["w2"] == "clerk")].iloc[:,2]
W1 = L_single[(L_single["w1"] == "head") & (L_single["w2"] == "clerk")].iloc[:,3]
W2  = L_single[(L_single["w1"] == "head") & (L_single["w2"] == "clerk")].iloc[:,4]

bigram_all = single_bigram
p= W2 / len(bigram_all)
b_1 = binom.pmf(W1W2,W1, p)
b_not_1 = binom.pmf((W2 - W1W2), (len(bigram_all)-W1), p)
L_H1 = b_1 * b_not_1

p_1 =W1W2 /W1
P_2 = (W2 -W1W2) / (len(bigram_all)-W1)
b_1_dep = binom.pmf(W1W2, W1, p_1)
b_not_1_dep = binom.pmf((W2 - W1W2), (len(bigram_all)- W1), P_2)
L_H2 = b_1_dep * b_not_1_dep
if L_H1 == 0:
  L_H1 = 1e-40
score = -2* np.log(L_H1/ L_H2)


In [ ]:
p,p_1,P_2,L_H1,L_H2,score

(127    0.000095
 Name: c(w2), dtype: float64,
 127    0.027466
 dtype: float64,
 127    0.00008
 dtype: float64,
 array([9.51927153e-49]),
 array([0.00320817]),
 array([209.66259424]))

In [ ]:
 L_single[(L_single["w1"] == "great") & (L_single["w2"] == "man")]

w1   w2  c(w1w2)  c(w1)  c(w2)   -2log(λ)
162  great  man       18   1202   2546  45.158744

In [ ]:
W1W2 = L_single[(L_single["w1"] == "great") & (L_single["w2"] == "man")].iloc[:,2]
W1 = L_single[(L_single["w1"] == "great") & (L_single["w2"] == "man")].iloc[:,3]
W2  = L_single[(L_single["w1"] == "great") & (L_single["w2"] == "man")].iloc[:,4]

bigram_all = single_bigram
p= W2 / len(bigram_all)
b_1 = binom.pmf(W1W2,W1, p)
b_not_1 = binom.pmf((W2 - W1W2), (len(bigram_all)-W1), p)
L_H1 = b_1 * b_not_1

p_1 =W1W2 /W1
P_2 = (W2 -W1W2) / (len(bigram_all)-W1)
b_1_dep = binom.pmf(W1W2, W1, p_1)
b_not_1_dep = binom.pmf((W2 - W1W2), (len(bigram_all)- W1), P_2)
L_H2 = b_1_dep * b_not_1_dep
if L_H1 == 0:
  L_H1 = 1e-40
score = -2* np.log(L_H1/ L_H2)
p,p_1,P_2,L_H1,L_H2,score

(162    0.001786
 Name: c(w2), dtype: float64,
 162    0.014975
 dtype: float64,
 162    0.001775
 dtype: float64,
 array([1.17040346e-13]),
 array([0.00074891]),
 array([45.15874384]))

In [ ]:
L_single = likelihood_test(single_counts, single_bigram)
L_triple = likelihood_test(triple_counts, double_bigram)

In [ ]:
L_sorted_single = L_single.sort_values(by=['-2log(λ)'], ascending = False)
L_sorted_single = L_sorted_single.reset_index()
L_sorted_single = L_sorted_single.drop(columns = ["index"])
L_sorted_single.to_csv("/content/drive/MyDrive/NLP Ödev 3/L-score_single.csv")

In [ ]:
L_sorted_triple = L_triple.sort_values(by=['-2log(λ)'], ascending = False)
L_sorted_triple = L_sorted_triple.reset_index()
L_sorted_triple = L_sorted_triple.drop(columns = ["index"])
L_sorted_triple.to_csv("/content/drive/MyDrive/NLP Ödev 3/L-score_triple.csv")

In [ ]:
L_sorted_single

w1            w2  c(w1w2)  c(w1)  c(w2)     -2log(λ)
0      evgenie    pavlovitch      106    227    461  1416.651221
1    pulcheria  alexandrovna       84    124    242  1335.791582
2       alexey  fyodorovitch       89    226    327  1215.475179
3       andrey   antonovitch       67    142     83  1191.599486
4         next           day      117    356   1711  1131.601040
..         ...           ...      ...    ...    ...          ...
352      whole          time       13    889   2623    31.364397
353     little          hand       11   1465   1578    23.479922
354     little           one       17   1465   4597    19.125834
355     little           man       12   1465   2546    17.884752
356     little          time       11   1465   2623    14.405366

[357 rows x 6 columns]

In [ ]:
L_single[(L_single["w1"] == "head") & (L_single["w2"] == "clerk")]

w1     w2  c(w1w2)  c(w1)  c(w2)    -2log(λ)
127  head  clerk       22    801    136  209.662594

In [ ]:
chi_single[(chi_single["w1"] == "head") & (chi_single["w2"] == "clerk")]

w1     w2  c(w1w2)  c(w1)  c(w2)  chi-square_score
127  head  clerk       22    801    136       6294.837113

In [ ]:
t_score_single[(t_score_single["w1"] == "head") & (t_score_single["w2"] == "clerk")]

w1     w2  c(w1w2)  c(w1)  c(w2)   t_score
127  head  clerk       22    801    136  4.687686

In [ ]:
L_single[(L_single["w1"] == "great") & (L_single["w2"] == "man")]

w1   w2  c(w1w2)  c(w1)  c(w2)   -2log(λ)
162  great  man       18   1202   2546  45.158744

In [ ]:
chi_single[(chi_single["w1"] == "great") & (chi_single["w2"] == "man")]

w1   w2  c(w1w2)  c(w1)  c(w2)  chi-square_score
162  great  man       18   1202   2546        117.484644

In [ ]:
t_score_single[(t_score_single["w1"] == "great") & (t_score_single["w2"] == "man")]

w1   w2  c(w1w2)  c(w1)  c(w2)   t_score
162  great  man       18   1202   2546  3.171056